apply plugin: 'java'
apply plugin: 'war'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'jakarta.ejb:jakarta.ejb-api:4.0.0'
    compileOnly 'jakarta.persistence:jakarta.persistence-api:3.0.0'

    implementation 'jakarta.enterprise:jakarta.enterprise.cdi-api:4.1.0'
    implementation 'jakarta.security.enterprise:jakarta.security.enterprise-api:3.0.0'

    implementation 'jakarta.transaction:jakarta.transaction-api'
    implementation 'org.postgresql:postgresql:42.7.8'
    implementation 'org.hibernate:hibernate-core:6.6.29.Final'

    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.1.0'
    compileOnly 'jakarta.ws.rs:jakarta.ws.rs-api:3.0.0'
}
